version: '3.4'

services:
  microservices-apigateway-product-api:
    image: acrmicroservicesapigatewayeac.azurecr.io/microservicesapigatewayproductapi
    ports:
      - "80"      
    build:
      context: .
      dockerfile: Microservices.APIGateway.Product.API/Dockerfile
  microservices-apigateway-sale-api:
    image: acrmicroservicesapigatewayeac.azurecr.io/microservicesapigatewaysaleapi
    ports:
      - "80"      
    build:
      context: .
      dockerfile: Microservices.APIGateway.Sale.API/Dockerfile
