version: '3.4'

services:
########################################################## mongodb ##################################################################################
  mongodb:
    image: mongo
    ports:
      - 27017:27017      
    networks:
      - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge

