// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microservice.Persistence.EFCore.Data.Contexts.Configurations;
using Microservice.Persistence.EFCore.Data.Entities;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System;

#nullable disable

namespace Microservice.Persistence.EFCore.Data.Contexts
{
    public partial class MicroservicePersistenceEFcoreContext : DbContext
    {
        public MicroservicePersistenceEFcoreContext()
        {
        }

        public MicroservicePersistenceEFcoreContext(DbContextOptions<MicroservicePersistenceEFcoreContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Product> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.OrderConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.OrderItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
